#!/bin/bash

BASEDIR=$(dirname "$0")

echo
echo "Digite a senha do super@mercurio"
read -s SSHPASS
echo
echo

echo "DESCOBRINDO ULTIMO BACKUP (senha super@mercurio)"
BACKUP=$(sshpass -p "$SSHPASS" ssh -o StrictHostKeyChecking=no super@mercurio.mgpapelaria.com.br "ls -1 -t /media/sdc1/backup/postgres | head -1")
if [ $? != 0 ] ; then
  echo erro
  exit
fi
echo $BACKUP
echo
echo

echo "COPIANDO ULTIMO BACKUP (senha super@mercurio)"
sshpass -p "$SSHPASS" rsync -avP super@mercurio.mgpapelaria.com.br:/media/sdc1/backup/postgres/$BACKUP /tmp/$BACKUP --progress
if [ $? != 0 ] ; then
  echo erro
  exit
fi
echo
echo

echo "PARANDO CONTAINER"
./$BASEDIR/stop
if [ $? != 0 ] ; then
  echo erro
  exit
fi
echo
echo

echo "LIMPANDO CONTAINER (senha sudo maquina local)"
sudo rm -rf ./$BASEDIR/.db
if [ $? != 0 ] ; then
  echo erro
  exit
fi
echo
echo

echo "INICIANDO CONTAINER"
./$BASEDIR/start-dev
if [ $? != 0 ] ; then
  echo erro
  exit
fi
echo
echo

echo "ESPERANDO 5 SEGUNDOS PARA CONTANER TERMINAR DE CARREGAR"
sleep 5
echo
echo

echo "VOLTANDO BACKUP"
docker-compose exec mgdb su - postgres -c "zcat /tmp/host/$BACKUP | psql"

echo
echo

echo "AJUSTANDO CADASTROS PARA MODO DESENVOLVIMENTO"
docker-compose exec mgdb su - postgres -c "psql -U mgsis -f /opt/www/MGdb/ajusta-cadastros.sql"
echo
echo
