services:
    mgdb:
        image: "postgres:14.1-alpine"
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - /opt/www:/opt/www
            - .:/home/host
            - ./.db/data:/var/lib/postgresql/data
            - /tmp:/tmp/host
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - /usr/share/zoneinfo:/usr/share/zoneinfo
        ports:
            - "5432:5432"
        extra_hosts:
            - "host.docker.internal:host-gateway"
