version: '3.3'
services:
    mgdb:
        image: "postgres:9.6.13"
        volumes:
            - ./.db/data:/var/lib/postgresql/data
            - /tmp:/tmp/host
        ports:
            - "54320:5432"
