#!/usr/bin/env bash
cd ~/Docker/MGdb
./start-dev
cd ~/Docker/MGLara
./start-dev
cd ~/Docker/MGsis
./start-dev
cd ~/Docker/MGUplon
./start-dev
cd ~/Docker/MGspa
./start-dev
echo "Agora entre na Shell (./shell) e Levante o Quasar (quasar dev -m pwa)"
